// Generated by gencpp from file pub_rospy/srv1.msg
// DO NOT EDIT!


#ifndef PUB_ROSPY_MESSAGE_SRV1_H
#define PUB_ROSPY_MESSAGE_SRV1_H

#include <ros/service_traits.h>


#include <pub_rospy/srv1Request.h>
#include <pub_rospy/srv1Response.h>


namespace pub_rospy
{

struct srv1
{

typedef srv1Request Request;
typedef srv1Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct srv1
} // namespace pub_rospy


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pub_rospy::srv1 > {
  static const char* value()
  {
    return "2a5c7a37218262bae4fcfaa1007692aa";
  }

  static const char* value(const ::pub_rospy::srv1&) { return value(); }
};

template<>
struct DataType< ::pub_rospy::srv1 > {
  static const char* value()
  {
    return "pub_rospy/srv1";
  }

  static const char* value(const ::pub_rospy::srv1&) { return value(); }
};


// service_traits::MD5Sum< ::pub_rospy::srv1Request> should match 
// service_traits::MD5Sum< ::pub_rospy::srv1 > 
template<>
struct MD5Sum< ::pub_rospy::srv1Request>
{
  static const char* value()
  {
    return MD5Sum< ::pub_rospy::srv1 >::value();
  }
  static const char* value(const ::pub_rospy::srv1Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::pub_rospy::srv1Request> should match 
// service_traits::DataType< ::pub_rospy::srv1 > 
template<>
struct DataType< ::pub_rospy::srv1Request>
{
  static const char* value()
  {
    return DataType< ::pub_rospy::srv1 >::value();
  }
  static const char* value(const ::pub_rospy::srv1Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pub_rospy::srv1Response> should match 
// service_traits::MD5Sum< ::pub_rospy::srv1 > 
template<>
struct MD5Sum< ::pub_rospy::srv1Response>
{
  static const char* value()
  {
    return MD5Sum< ::pub_rospy::srv1 >::value();
  }
  static const char* value(const ::pub_rospy::srv1Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::pub_rospy::srv1Response> should match 
// service_traits::DataType< ::pub_rospy::srv1 > 
template<>
struct DataType< ::pub_rospy::srv1Response>
{
  static const char* value()
  {
    return DataType< ::pub_rospy::srv1 >::value();
  }
  static const char* value(const ::pub_rospy::srv1Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PUB_ROSPY_MESSAGE_SRV1_H
