// Generated by gencpp from file pub_rospy/total.msg
// DO NOT EDIT!


#ifndef PUB_ROSPY_MESSAGE_TOTAL_H
#define PUB_ROSPY_MESSAGE_TOTAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <pub_rospy/pubmsg.h>
#include <std_msgs/Header.h>

namespace pub_rospy
{
template <class ContainerAllocator>
struct total_
{
  typedef total_<ContainerAllocator> Type;

  total_()
    : result()
    , header()  {
    }
  total_(const ContainerAllocator& _alloc)
    : result(_alloc)
    , header(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::pub_rospy::pubmsg_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::pub_rospy::pubmsg_<ContainerAllocator> >::other >  _result_type;
  _result_type result;

   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;





  typedef boost::shared_ptr< ::pub_rospy::total_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pub_rospy::total_<ContainerAllocator> const> ConstPtr;

}; // struct total_

typedef ::pub_rospy::total_<std::allocator<void> > total;

typedef boost::shared_ptr< ::pub_rospy::total > totalPtr;
typedef boost::shared_ptr< ::pub_rospy::total const> totalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pub_rospy::total_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pub_rospy::total_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pub_rospy

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsMessage': True, 'IsFixedSize': False, 'HasHeader': False}
// {'pub_rospy': ['/home/dd/rospy_rs2/src/pub_rospy/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsMessage< ::pub_rospy::total_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pub_rospy::total_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pub_rospy::total_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pub_rospy::total_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pub_rospy::total_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pub_rospy::total_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pub_rospy::total_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0c72830414d9245ad5dfa266b3a9c646";
  }

  static const char* value(const ::pub_rospy::total_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0c72830414d9245aULL;
  static const uint64_t static_value2 = 0xd5dfa266b3a9c646ULL;
};

template<class ContainerAllocator>
struct DataType< ::pub_rospy::total_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pub_rospy/total";
  }

  static const char* value(const ::pub_rospy::total_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pub_rospy::total_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pubmsg[] result\n\
std_msgs/Header header\n\
\n\
================================================================================\n\
MSG: pub_rospy/pubmsg\n\
float32 label\n\
float32 confidence\n\
float32 x\n\
float32 y\n\
float32 z\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::pub_rospy::total_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pub_rospy::total_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
      stream.next(m.header);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct total_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pub_rospy::total_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pub_rospy::total_<ContainerAllocator>& v)
  {
    s << indent << "result[]" << std::endl;
    for (size_t i = 0; i < v.result.size(); ++i)
    {
      s << indent << "  result[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::pub_rospy::pubmsg_<ContainerAllocator> >::stream(s, indent + "    ", v.result[i]);
    }
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PUB_ROSPY_MESSAGE_TOTAL_H
