// Generated by gencpp from file pub_rospy/pubmsg.msg
// DO NOT EDIT!


#ifndef PUB_ROSPY_MESSAGE_PUBMSG_H
#define PUB_ROSPY_MESSAGE_PUBMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pub_rospy
{
template <class ContainerAllocator>
struct pubmsg_
{
  typedef pubmsg_<ContainerAllocator> Type;

  pubmsg_()
    : label(0.0)
    , confidence(0.0)
    , x(0.0)
    , y(0.0)
    , z(0.0)  {
    }
  pubmsg_(const ContainerAllocator& _alloc)
    : label(0.0)
    , confidence(0.0)
    , x(0.0)
    , y(0.0)
    , z(0.0)  {
  (void)_alloc;
    }



   typedef float _label_type;
  _label_type label;

   typedef float _confidence_type;
  _confidence_type confidence;

   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::pub_rospy::pubmsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pub_rospy::pubmsg_<ContainerAllocator> const> ConstPtr;

}; // struct pubmsg_

typedef ::pub_rospy::pubmsg_<std::allocator<void> > pubmsg;

typedef boost::shared_ptr< ::pub_rospy::pubmsg > pubmsgPtr;
typedef boost::shared_ptr< ::pub_rospy::pubmsg const> pubmsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pub_rospy::pubmsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pub_rospy::pubmsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pub_rospy

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsMessage': True, 'IsFixedSize': True, 'HasHeader': False}
// {'pub_rospy': ['/home/dd/rospy_rs2/src/pub_rospy/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsMessage< ::pub_rospy::pubmsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pub_rospy::pubmsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pub_rospy::pubmsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pub_rospy::pubmsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pub_rospy::pubmsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pub_rospy::pubmsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pub_rospy::pubmsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d681388b870b81593f8e8878a8139340";
  }

  static const char* value(const ::pub_rospy::pubmsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd681388b870b8159ULL;
  static const uint64_t static_value2 = 0x3f8e8878a8139340ULL;
};

template<class ContainerAllocator>
struct DataType< ::pub_rospy::pubmsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pub_rospy/pubmsg";
  }

  static const char* value(const ::pub_rospy::pubmsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pub_rospy::pubmsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 label\n\
float32 confidence\n\
float32 x\n\
float32 y\n\
float32 z\n\
";
  }

  static const char* value(const ::pub_rospy::pubmsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pub_rospy::pubmsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.label);
      stream.next(m.confidence);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pubmsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pub_rospy::pubmsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pub_rospy::pubmsg_<ContainerAllocator>& v)
  {
    s << indent << "label: ";
    Printer<float>::stream(s, indent + "  ", v.label);
    s << indent << "confidence: ";
    Printer<float>::stream(s, indent + "  ", v.confidence);
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PUB_ROSPY_MESSAGE_PUBMSG_H
